DROP TABLE IF EXISTS ability CASCADE;
DROP TABLE IF EXISTS "Towers" CASCADE;
DROP TABLE IF EXISTS ability_level;
DROP TABLE IF EXISTS main_stats;
DROP TABLE IF EXISTS attack_stats;
DROP TABLE IF EXISTS barracks_stats;
DROP TABLE IF EXISTS build_sequence;
DROP TYPE IF EXISTS "Towers_towertype_enum";
DROP TYPE IF EXISTS "Towers_level_enum";
DROP TYPE IF EXISTS "Towers_kingdom_enum";
DROP TABLE IF EXISTS migrations;